version: "3.9"
services:
  api:
    build: .
    container_name: pmgenie_api
    env_file:
      - creds.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - qdrant
      - localstack
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: pmgenie_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pmgenie
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: pmgenie_qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  localstack:
    image: localstack/localstack:2.3
    container_name: pmgenie_localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    ports:
      - "4567:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  pgdata:
  qdrant_storage:
  localstack_data:
